# -*- coding: utf-8 -*-
"""ArtificialIntelligenceLec1_.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pCgDThVT8rHyABgai2lJ-vtuE_bJ4wqT
"""

#Q1

import math
import os
import random
import re
import sys

n = int(input().strip())

if n % 2 != 0:
    print("Weird")
else:
    if n >= 2 and n <= 5:
        print ("Not Weird")
    elif n >= 6 and n <= 20:
        print ("Weird")
    elif n > 20:
        print ("Not Weird")

#Q2
if __name__ == '__main__':
    a = int(input())
    b = int(input())

print(a+b)
print(a-b)
print(a*b)

#Q3
if __name__ == '__main__':
    a = int(input())
    b = int(input())
print(int(a//b))
print(float(a/b))

#Q4
if __name__ == '__main__':
    n = int(input())
for i in range(n):
    print(i*i)

#Q5
n=int(input())

for i in range(n):    
    print(i+1, end="")

#Q6
if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())

ans = [[i, j, k] for i in range(x + 1) for j in range(y + 1) for k in range(z + 1) if i + j + k != n]
print(ans)